StylesPath = .github/doc/styles
MinAlertLevel = suggestion


Vocab = Sphinx

[*.rst]
BasedOnStyles = ADI, Vale, Google
# Ignore code blocks and inline code
BlockIgnores = (?s) *(?:\.\. code-block::.*?)\n\n, (?s)(?:```.*)```
TokenIgnores = (?s)`[^`]+`, (?s)``[^`]+``

[*.md]
BasedOnStyles = ADI, Vale, Google
# Ignore code blocks and inline code
BlockIgnores = (?s) *(?:```.*?)```
TokenIgnores = (?s)`[^`]+`
