# Copyright (c) 2026 Analog Devices, Inc.
# SPDX-License-Identifier: MIT

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: acd6be722fcc3f87eeedb796d96a627a24b0b3e1
      clone-depth: 1
      import:
        name-allowlist:
          - cmsis_6
          - hal_adi
          - hal_nordic
          - hal_nxp
          - hal_rpi_pico
          - hal_stm32
          - hal_st
          - net-tools
          - picolibc
