# Copyright (c) 2026 Analog Devices, Inc.
# SPDX-License-Identifier: MIT

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: b1e130ee3ab3c7a662de97909c664cfa2c591a6f
      clone-depth: 1
      import:
        name-allowlist:
          - cmsis_6
          - hal_adi
          - hal_nordic
          - hal_nxp
          - hal_rpi_pico
          - hal_stm32
          - hal_st
          - net-tools
          - picolibc
