# Copyright (c) 2026 Analog Devices, Inc.
# SPDX-License-Identifier: MIT
#
# Multi-sensor: ADXL345 (real HW) + ADLTC2990 (emulated)

CONFIG_SENSOR=y
CONFIG_I2C=y

CONFIG_ADXL345=y
CONFIG_ADC=y

CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_EMUL=y
CONFIG_EMUL_ADLTC2990=y
CONFIG_I2C_EMUL=y
