# Copyright (c) 2025 Analog Devices, Inc.
# SPDX-License-Identifier: MIT

CONFIG_ADC=y

CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_LIBIIO_IIO_DEVICE_FP=y
CONFIG_LIBIIO_IIO_DEVICE_IO_CHANNELS_INIT_PRIORITY=90
