/*
 * Copyright (c) 2025 Analog Devices, Inc.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_IIO_SENSOR_CHANNELS_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_IIO_SENSOR_CHANNELS_H_

/* Sensor channel definitions for devicetree
 * These mirror enum sensor_channel from zephyr/drivers/sensor.h
 */

#define IIO_SENSOR_CHAN_ACCEL_X				0
#define IIO_SENSOR_CHAN_ACCEL_Y				(IIO_SENSOR_CHAN_ACCEL_X + 1)
#define IIO_SENSOR_CHAN_ACCEL_Z				(IIO_SENSOR_CHAN_ACCEL_Y + 1)
#define IIO_SENSOR_CHAN_ACCEL_XYZ			(IIO_SENSOR_CHAN_ACCEL_Z + 1)
#define IIO_SENSOR_CHAN_GYRO_X				(IIO_SENSOR_CHAN_ACCEL_XYZ + 1)
#define IIO_SENSOR_CHAN_GYRO_Y				(IIO_SENSOR_CHAN_GYRO_X + 1)
#define IIO_SENSOR_CHAN_GYRO_Z				(IIO_SENSOR_CHAN_GYRO_Y + 1)
#define IIO_SENSOR_CHAN_GYRO_XYZ			(IIO_SENSOR_CHAN_GYRO_Z + 1)
#define IIO_SENSOR_CHAN_MAGN_X				(IIO_SENSOR_CHAN_GYRO_XYZ + 1)
#define IIO_SENSOR_CHAN_MAGN_Y				(IIO_SENSOR_CHAN_MAGN_X + 1)
#define IIO_SENSOR_CHAN_MAGN_Z				(IIO_SENSOR_CHAN_MAGN_Y + 1)
#define IIO_SENSOR_CHAN_MAGN_XYZ			(IIO_SENSOR_CHAN_MAGN_Z + 1)

#define IIO_SENSOR_CHAN_DIE_TEMP			(IIO_SENSOR_CHAN_MAGN_XYZ + 1)
#define IIO_SENSOR_CHAN_AMBIENT_TEMP			(IIO_SENSOR_CHAN_DIE_TEMP + 1)

#define IIO_SENSOR_CHAN_PRESS				(IIO_SENSOR_CHAN_AMBIENT_TEMP + 1)
#define IIO_SENSOR_CHAN_PROX				(IIO_SENSOR_CHAN_PRESS + 1)
#define IIO_SENSOR_CHAN_HUMIDITY			(IIO_SENSOR_CHAN_PROX + 1)
#define IIO_SENSOR_CHAN_AMBIENT_LIGHT			(IIO_SENSOR_CHAN_HUMIDITY + 1)
#define IIO_SENSOR_CHAN_LIGHT				(IIO_SENSOR_CHAN_AMBIENT_LIGHT + 1)
#define IIO_SENSOR_CHAN_IR				(IIO_SENSOR_CHAN_LIGHT + 1)
#define IIO_SENSOR_CHAN_RED				(IIO_SENSOR_CHAN_IR + 1)
#define IIO_SENSOR_CHAN_GREEN				(IIO_SENSOR_CHAN_RED + 1)
#define IIO_SENSOR_CHAN_BLUE				(IIO_SENSOR_CHAN_GREEN + 1)
#define IIO_SENSOR_CHAN_ALTITUDE			(IIO_SENSOR_CHAN_BLUE + 1)

#define IIO_SENSOR_CHAN_PM_1_0_CF			(IIO_SENSOR_CHAN_ALTITUDE + 1)
#define IIO_SENSOR_CHAN_PM_2_5_CF			(IIO_SENSOR_CHAN_PM_1_0_CF + 1)
#define IIO_SENSOR_CHAN_PM_10_CF			(IIO_SENSOR_CHAN_PM_2_5_CF + 1)
#define IIO_SENSOR_CHAN_PM_1_0				(IIO_SENSOR_CHAN_PM_10_CF + 1)
#define IIO_SENSOR_CHAN_PM_2_5				(IIO_SENSOR_CHAN_PM_1_0 + 1)
#define IIO_SENSOR_CHAN_PM_10				(IIO_SENSOR_CHAN_PM_2_5 + 1)
#define IIO_SENSOR_CHAN_PM_0_3_COUNT			(IIO_SENSOR_CHAN_PM_10 + 1)
#define IIO_SENSOR_CHAN_PM_0_5_COUNT			(IIO_SENSOR_CHAN_PM_0_3_COUNT + 1)
#define IIO_SENSOR_CHAN_PM_1_0_COUNT			(IIO_SENSOR_CHAN_PM_0_5_COUNT + 1)
#define IIO_SENSOR_CHAN_PM_2_5_COUNT			(IIO_SENSOR_CHAN_PM_1_0_COUNT + 1)
#define IIO_SENSOR_CHAN_PM_5_COUNT			(IIO_SENSOR_CHAN_PM_2_5_COUNT + 1)
#define IIO_SENSOR_CHAN_PM_10_COUNT			(IIO_SENSOR_CHAN_PM_5_COUNT + 1)
#define IIO_SENSOR_CHAN_DISTANCE			(IIO_SENSOR_CHAN_PM_10_COUNT + 1)

#define IIO_SENSOR_CHAN_CO2				(IIO_SENSOR_CHAN_DISTANCE + 1)
#define IIO_SENSOR_CHAN_O2				(IIO_SENSOR_CHAN_CO2 + 1)
#define IIO_SENSOR_CHAN_VOC				(IIO_SENSOR_CHAN_O2 + 1)
#define IIO_SENSOR_CHAN_GAS_RES				(IIO_SENSOR_CHAN_VOC + 1)
#define IIO_SENSOR_CHAN_FLOW_RATE			(IIO_SENSOR_CHAN_GAS_RES + 1)

#define IIO_SENSOR_CHAN_VOLTAGE				(IIO_SENSOR_CHAN_FLOW_RATE + 1)
#define IIO_SENSOR_CHAN_VSHUNT				(IIO_SENSOR_CHAN_VOLTAGE + 1)
#define IIO_SENSOR_CHAN_CURRENT				(IIO_SENSOR_CHAN_VSHUNT + 1)
#define IIO_SENSOR_CHAN_POWER				(IIO_SENSOR_CHAN_CURRENT + 1)
#define IIO_SENSOR_CHAN_RESISTANCE			(IIO_SENSOR_CHAN_POWER + 1)

#define IIO_SENSOR_CHAN_ROTATION			(IIO_SENSOR_CHAN_RESISTANCE + 1)
#define IIO_SENSOR_CHAN_POS_DX				(IIO_SENSOR_CHAN_ROTATION + 1)
#define IIO_SENSOR_CHAN_POS_DY				(IIO_SENSOR_CHAN_POS_DX + 1)
#define IIO_SENSOR_CHAN_POS_DZ				(IIO_SENSOR_CHAN_POS_DY + 1)
#define IIO_SENSOR_CHAN_POS_DXYZ			(IIO_SENSOR_CHAN_POS_DZ + 1)
#define IIO_SENSOR_CHAN_RPM				(IIO_SENSOR_CHAN_POS_DXYZ + 1)
#define IIO_SENSOR_CHAN_FREQUENCY			(IIO_SENSOR_CHAN_RPM + 1)

#define IIO_SENSOR_CHAN_GAUGE_VOLTAGE			(IIO_SENSOR_CHAN_FREQUENCY + 1)
#define IIO_SENSOR_CHAN_GAUGE_AVG_CURRENT		(IIO_SENSOR_CHAN_GAUGE_VOLTAGE + 1)
#define IIO_SENSOR_CHAN_GAUGE_STDBY_CURRENT		(IIO_SENSOR_CHAN_GAUGE_AVG_CURRENT + 1)
#define IIO_SENSOR_CHAN_GAUGE_MAX_LOAD_CURRENT		(IIO_SENSOR_CHAN_GAUGE_STDBY_CURRENT + 1)
#define IIO_SENSOR_CHAN_GAUGE_TEMP			(IIO_SENSOR_CHAN_GAUGE_MAX_LOAD_CURRENT + 1)
#define IIO_SENSOR_CHAN_GAUGE_STATE_OF_CHARGE		(IIO_SENSOR_CHAN_GAUGE_TEMP + 1)
#define IIO_SENSOR_CHAN_GAUGE_FULL_CHARGE_CAPACITY	(IIO_SENSOR_CHAN_GAUGE_STATE_OF_CHARGE + 1)
#define IIO_SENSOR_CHAN_GAUGE_REMAINING_CHARGE_CAPACITY	(IIO_SENSOR_CHAN_GAUGE_FULL_CHARGE_CAPACITY + 1)
#define IIO_SENSOR_CHAN_GAUGE_NOM_AVAIL_CAPACITY	(IIO_SENSOR_CHAN_GAUGE_REMAINING_CHARGE_CAPACITY + 1)
#define IIO_SENSOR_CHAN_GAUGE_FULL_AVAIL_CAPACITY	(IIO_SENSOR_CHAN_GAUGE_NOM_AVAIL_CAPACITY + 1)
#define IIO_SENSOR_CHAN_GAUGE_AVG_POWER			(IIO_SENSOR_CHAN_GAUGE_FULL_AVAIL_CAPACITY + 1)
#define IIO_SENSOR_CHAN_GAUGE_STATE_OF_HEALTH		(IIO_SENSOR_CHAN_GAUGE_AVG_POWER + 1)
#define IIO_SENSOR_CHAN_GAUGE_TIME_TO_EMPTY		(IIO_SENSOR_CHAN_GAUGE_STATE_OF_HEALTH + 1)
#define IIO_SENSOR_CHAN_GAUGE_TIME_TO_FULL		(IIO_SENSOR_CHAN_GAUGE_TIME_TO_EMPTY + 1)
#define IIO_SENSOR_CHAN_GAUGE_CYCLE_COUNT		(IIO_SENSOR_CHAN_GAUGE_TIME_TO_FULL + 1)
#define IIO_SENSOR_CHAN_GAUGE_DESIGN_VOLTAGE		(IIO_SENSOR_CHAN_GAUGE_CYCLE_COUNT + 1)
#define IIO_SENSOR_CHAN_GAUGE_DESIRED_VOLTAGE		(IIO_SENSOR_CHAN_GAUGE_DESIGN_VOLTAGE + 1)
#define IIO_SENSOR_CHAN_GAUGE_DESIRED_CHARGING_CURRENT	(IIO_SENSOR_CHAN_GAUGE_DESIRED_VOLTAGE + 1)
#define IIO_SENSOR_CHAN_GAME_ROTATION_VECTOR		(IIO_SENSOR_CHAN_GAUGE_DESIRED_CHARGING_CURRENT + 1)
#define IIO_SENSOR_CHAN_GRAVITY_VECTOR			(IIO_SENSOR_CHAN_GAME_ROTATION_VECTOR + 1)
#define IIO_SENSOR_CHAN_GBIAS_XYZ			(IIO_SENSOR_CHAN_GRAVITY_VECTOR + 1)
#define IIO_SENSOR_CHAN_ENCODER_COUNT			(IIO_SENSOR_CHAN_GBIAS_XYZ + 1)

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_IIO_SENSOR_CHANNELS_H_ */
