/*
 * Copyright (c) 2025 Analog Devices, Inc.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_IIO_SENSOR_CHANNELS_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_IIO_SENSOR_CHANNELS_H_

/* Sensor channel definitions for devicetree
 * These mirror enum sensor_channel from zephyr/drivers/sensor.h
 */

#define IIO_SENSOR_CHAN_ACCEL_X				0
#define IIO_SENSOR_CHAN_ACCEL_Y				1
#define IIO_SENSOR_CHAN_ACCEL_Z				2
#define IIO_SENSOR_CHAN_ACCEL_XYZ			3
#define IIO_SENSOR_CHAN_GYRO_X				4
#define IIO_SENSOR_CHAN_GYRO_Y				5
#define IIO_SENSOR_CHAN_GYRO_Z				6
#define IIO_SENSOR_CHAN_GYRO_XYZ			7
#define IIO_SENSOR_CHAN_MAGN_X				8
#define IIO_SENSOR_CHAN_MAGN_Y				9
#define IIO_SENSOR_CHAN_MAGN_Z				10
#define IIO_SENSOR_CHAN_MAGN_XYZ			11

#define IIO_SENSOR_CHAN_DIE_TEMP			12
#define IIO_SENSOR_CHAN_AMBIENT_TEMP	13

#define IIO_SENSOR_CHAN_PRESS					14
#define IIO_SENSOR_CHAN_PROX					15
#define IIO_SENSOR_CHAN_HUMIDITY			16
#define IIO_SENSOR_CHAN_AMBIENT_LIGHT	17
#define IIO_SENSOR_CHAN_LIGHT					18
#define IIO_SENSOR_CHAN_IR						19
#define IIO_SENSOR_CHAN_RED						20
#define IIO_SENSOR_CHAN_GREEN					21
#define IIO_SENSOR_CHAN_BLUE					22
#define IIO_SENSOR_CHAN_ALTITUDE			23

#define IIO_SENSOR_CHAN_PM_1_0_CF			24
#define IIO_SENSOR_CHAN_PM_2_5_CF			25
#define IIO_SENSOR_CHAN_PM_10_CF			26
#define IIO_SENSOR_CHAN_PM_1_0				27
#define IIO_SENSOR_CHAN_PM_2_5				28
#define IIO_SENSOR_CHAN_PM_10					29
#define IIO_SENSOR_CHAN_PM_0_3_COUNT	30
#define IIO_SENSOR_CHAN_PM_0_5_COUNT	31
#define IIO_SENSOR_CHAN_PM_1_0_COUNT	32
#define IIO_SENSOR_CHAN_PM_2_5_COUNT	33
#define IIO_SENSOR_CHAN_PM_5_COUNT		34
#define IIO_SENSOR_CHAN_PM_10_COUNT		35
#define IIO_SENSOR_CHAN_DISTANCE			36

#define IIO_SENSOR_CHAN_CO2						37
#define IIO_SENSOR_CHAN_O2						38
#define IIO_SENSOR_CHAN_VOC						39
#define IIO_SENSOR_CHAN_GAS_RES				40
#define IIO_SENSOR_CHAN_FLOW_RATE			41

#define IIO_SENSOR_CHAN_VOLTAGE				42
#define IIO_SENSOR_CHAN_VSHUNT				43
#define IIO_SENSOR_CHAN_CURRENT				44
#define IIO_SENSOR_CHAN_POWER					45
#define IIO_SENSOR_CHAN_RESISTANCE		46

#define IIO_SENSOR_CHAN_ROTATION			47
#define IIO_SENSOR_CHAN_POS_DX				48
#define IIO_SENSOR_CHAN_POS_DY				49
#define IIO_SENSOR_CHAN_POS_DZ				50
#define IIO_SENSOR_CHAN_POS_DXYZ			51
#define IIO_SENSOR_CHAN_RPM						52
#define IIO_SENSOR_CHAN_FREQUENCY			53

#define IIO_SENSOR_CHAN_GAUGE_VOLTAGE						54
#define IIO_SENSOR_CHAN_GAUGE_AVG_CURRENT				55
#define IIO_SENSOR_CHAN_GAUGE_STDBY_CURRENT			56
#define IIO_SENSOR_CHAN_GAUGE_MAX_LOAD_CURRENT	57
#define IIO_SENSOR_CHAN_GAUGE_TEMP							58
#define IIO_SENSOR_CHAN_GAUGE_STATE_OF_CHARGE		59

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_IIO_SENSOR_CHANNELS_H_ */
