#!/bin/sh

cd $TRAVIS_BUILD_DIR

check_file()
{
temp=$(find ./build* -maxdepth 1 -name "*.$1")
if [ "$(echo ${temp} | wc -w)" -gt "1"  ] ; then
	echo "I am confused - more than 2 $1 files"
	echo $temp
	exit
fi
}

check_file deb
if [ -n "${temp}" ] ; then
	export TARGET_DEB=$(echo ${temp} | \
		sed -e 's:^./.*/::' -e 's:.deb$::')${LDIST}.deb
	echo "deploying ${temp} to nightly $TARGET_DEB"
	cp ${temp} ${TARGET_DEB}
	export RELEASE_PKG_FILE_DEB=./build/${TARGET_DEB}
	ls -lh ${temp}
else
	echo "Skipping deployment of debian package"
fi

check_file rpm
if [ -n "${temp}" ] ; then
	export TARGET_RPM=$(echo ${temp} | \
		sed -e 's:^./.*/::' -e 's:.rpm$::')${LDIST}.rpm
	echo "deploying ${temp} to nightly $TARGET_RPM"
	cp ${temp} ${TARGET_RPM}
	export RELEASE_PKG_FILE_RPM=./build/${TARGET_RPM}
	ls -lh ${temp}
else
	echo "Skipping deployment of rpm package"
fi

check_file tar.gz
if [  -n "${temp}"  ] ; then
	# Add the MATLAB bindings into the tar file
	(
		cd $(dirname ${temp})

		mkdir tarball_fixup && cd tarball_fixup

		if [ "$TRAVIS_OS_NAME" = "osx" ] ; then
			tar --strip-components=1 -xzf ${TRAVIS_BUILD_DIR}/${temp}
		else
			tar -xzf ${TRAVIS_BUILD_DIR}/${temp}
		fi

		mkdir -p usr/include usr/lib/matlab/iio
		cp ${TRAVIS_BUILD_DIR}/bindings/matlab/iio-wrapper.h usr/include/
		cp ${TRAVIS_BUILD_DIR}/bindings/matlab/*.m usr/lib/matlab/iio/

		if [ "$TRAVIS_OS_NAME" = "osx" ] ; then
			cd usr/lib
			ln -fs ../../Library/Frameworks/iio.framework/iio libiio.dylib
			install_name_tool -change /usr/local/opt/libusb/lib/libusb-1.0.0.dylib @rpath/libusb-1.0.dylib libiio.dylib
			install_name_tool -add_rpath @loader_path/../../../../../usr/lib libiio.dylib
			install_name_tool -add_rpath /usr/local/opt/libusb/lib libiio.dylib

			cd ../include
			ln -s ../../Library/Frameworks/iio.framework/Headers/iio.h iio.h

			# Update references for tools
			cd ../..
			TOOLS=Library/Frameworks/iio.framework/Tools/*
			for tool in $TOOLS
			do
				install_name_tool -add_rpath @loader_path/../../ $tool
			done
			cp /usr/local/lib/libusb-1.0.dylib usr/lib/
			chmod +w usr/lib/libusb-1.0.dylib
			install_name_tool -id @rpath/libusb-1.0.dylib usr/lib/libusb-1.0.dylib

			tar -czf ${TRAVIS_BUILD_DIR}/${temp} usr Library
		else
			tar -czf ${TRAVIS_BUILD_DIR}/${temp} usr lib
		fi
	)

	export TARGET_TGZ=$(echo ${temp} | \
		sed -e 's:^./.*/::' -e 's:.tar.gz$::')${LDIST}.tar.gz;
	echo "deploying ${temp} to $TARGET_TGZ"
	cp ${temp} ${TARGET_TGZ}
	export RELEASE_PKG_FILE_TGZ=./build/${TARGET_TGZ}
	ls -lh ${temp}
else
	echo "Skipping deployment of tarball"
fi

check_file pkg
if [ -n "${temp}" ] ; then
	export TARGET_PKG=$(echo ${temp} | \
		sed -e 's:^./.*/::' -e 's:.pkg$::')${LDIST}.pkg
	echo "deploying ${temp} to nightly $TARGET_PKG"
	cp ${temp} ${TARGET_PKG}
	export RELEASE_PKG_FILE_PKG=./build/${TARGET_PKG}
	ls -lh ${temp}
else
	echo "Skipping deployment of OS X package"
fi

