#!/bin/sh

brew update
if ! brew ls --version cmake &>/dev/null; then
	brew install cmake
else
	brew upgrade cmake
fi
brew install doxygen
brew install --build-from-source libusb
brew install libxml2
