#!/bin/sh -xe

. CI/travis/lib.sh

#    from                   to             suffix
send ${RELEASE_PKG_FILE_DEB} ${TARGET_DEB} .deb
send ${RELEASE_PKG_FILE_RPM} ${TARGET_RPM} .rpm
send ${RELEASE_PKG_FILE_TGZ} ${TARGET_TGZ} .tar.gz
send ${RELEASE_PKG_FILE_PKG} ${TARGET_PKG} .pkg

