#!/bin/sh
##### Setup this script and get the current gh-pages branch. #####
echo 'Setting up the script...'
# Exit with nonzero exit code if anything fails
set -e

# Create a clean working directory for this script.
mkdir code_docs
cd code_docs

# Get the current gh-pages branch
git clone https://git@$GH_REPO_REF
cd $GH_REPO_NAME

##### Configure git.
# Set the push default to simple i.e. push only the current branch.
git config --global push.default simple
# Pretend to be an user called Travis CI.
git config user.name "Travis CI"
git config user.email "travis@travis-ci.org"

# Remove everything currently in the gh-pages branch.
# GitHub is smart enough to know which files have changed and which files have
# stayed the same and will only update the changed files. So the gh-pages branch
# can be safely cleaned, and it is sure that everything pushed later is the new
# documentation.
rm -rf *

# Need to create a .nojekyll file to allow filenames starting with an underscore
# to be seen on the gh-pages site. Therefore creating an empty .nojekyll file.
# Presumably this is only needed when the SHORT_NAMES option in Doxygen is set
# to NO, which it is by default. So creating the file just in case.
echo "" > .nojekyll

# We want to update docs only on releases, so we check for tags

TAG="$(git describe --tags)"
ABBREV_TAG="$(git describe --tags --abbrev=0)"
git checkout gh-pages

################################################################################
##### Generate the Doxygen code documentation and log the output.          #####
echo 'Generating Doxygen code documentation...'
# Redirect both stderr and stdout to the log file AND the console.
doxygen $DOXYFILE 2>&1 | tee doxygen.log

################################################################################
##### Upload the documentation to the gh-pages branch of the repository.   #####
# Check for html/ and html/index.html

if [ -d "html" ] && [ -f "html/index.html" ]; then
	cp -R html/* .
	rm -rf html
	
	if [ "$TAG" = "$ABBREV_TAG" ]; then
		echo 'Uploading documentation to the gh-pages branch...'
		# Add everything in this directory (the Doxygen code documentation) to the
		# gh-pages branch.
		# GitHub is smart enough to know which files have changed and which files have
		# stayed the same and will only update the changed files.
		git add --all

		# Commit the added files with a title and description containing the Travis CI
		# build number and the GitHub commit reference that issued this build.
		git commit -m "Deploy code docs to GitHub Pages"

		# Force push to the remote gh-pages branch.
		# The ouput is redirected to /dev/null to hide any sensitive credential data
		# that might otherwise be exposed.
		echo 'Push to the remote gh-pages branch...'
		git push --force "https://${GH_REPO_TOKEN}@${GH_REPO_REF}" > /dev/null 2>&1
	fi
else
    echo '' >&2
    echo 'Warning: No documentation (html) files have been found!' >&2
    echo 'Warning: Not going to push the documentation to GitHub!' >&2
    exit 1
fi