#!/bin/sh

cd $TRAVIS_BUILD_DIR

send()
{
if [ "$#" -ne 3 ] ; then
	echo "skipping deployment of something"
        echo "send called with $@"
	return
fi

if [ "x$1" = "x" ] ; then
	echo no file to send
	return
fi

if [ ! -r "$1" ] ; then
	echo "file $1 is not readable"
	ls -l $1
	return
fi

FROM=$1
TO=$2
LATE=latest_libiio${LDIST}$3
GLOB=${DEPLOY_TO}/libiio-*

echo attemting to deploy $1 to $2
echo and latest_libiio${LDIST}$3
cp ${FROM} ${TO}
cp ${FROM} ${LATE}
ssh -V
scp ${EXTRA_SSH} ${TO} ${SSHUSER}@${SSHHOST}:${DEPLOY_TO}/
ssh ${EXTRA_SSH} ${SSHUSER}@${SSHHOST} "rm -f ${DEPLOY_TO}/${LATE}"
scp ${EXTRA_SSH} ${LATE} ${SSHUSER}@${SSHHOST}:${DEPLOY_TO}/

# there is some issue with the travis-ci / OSX implmentation - this
# doesn't work on that platform, so we just copy it above, vs linking it
#	ssh ${EXTRA_SSH} ${SSHUSER}@${SSHHOST} "rm ${LATE}"
#	ssh ${EXTRA_SSH} ${SSHUSER}@${SSHHOST} "ln ${TO} ${LATE}"

if [ "${LDIST}" = "-precise" -a "$3" = ".deb" ] ; then
	# yeah, I know this is bad, but there are some ssh issues, that are
	# unable to figure out, and this is a nasty hack
	ssh ${EXTRA_SSH} ${SSHUSER}@${SSHHOST} "rm ${DEPLOY_TO}/latest_libiio-osx*"
	for files in $(ssh ${EXTRA_SSH} ${SSHUSER}@${SSHHOST} \
		"ls -lt ${GLOB}" | tail -n +100 | awk '{print $NF}')
	do
		ssh ${EXTRA_SSH} ${SSHUSER}@${SSHHOST} \
			"rm ${DEPLOY_TO}/${files}"
	done
fi
}

#    from                   to             suffix
send ${RELEASE_PKG_FILE_DEB} ${TARGET_DEB} .deb
send ${RELEASE_PKG_FILE_RPM} ${TARGET_RPM} .rpm
send ${RELEASE_PKG_FILE_TGZ} ${TARGET_TGZ} .tar.gz
send ${RELEASE_PKG_FILE_PKG} ${TARGET_PKG} .pkg

