#!/bin/sh -xe

if [ "x${COVERITY_SCAN_PROJECT_NAME}" != "x" ] ; then exit 0; fi

handle_default() {
	cd $TRAVIS_BUILD_DIR/build
	cmake -DENABLE_PACKAGING=ON -DDEB_DETECT_DEPENDENCIES=ON ..
	make && make package
}

handle_centos() {
	sudo docker run --rm=true \
		-v `pwd`:/libiio:rw \
		centos:centos${OS_VERSION} \
		/bin/bash -xe /libiio/CI/travis/inside_centos_docker.sh ${OS_VERSION} travis-ci
}

OS_TYPE=${1:-default}
OS_VERSION="$2"

handle_${OS_TYPE}

