#!/bin/sh -e

if [ "x${COVERITY_SCAN_PROJECT_NAME}" != "x" ] ; then exit 0; fi

cd $TRAVIS_BUILD_DIR/build
cmake -DOSX_PACKAGE=ON ..
make
ls

cd $TRAVIS_BUILD_DIR/build_tar
cmake -DOSX_PACKAGE=OFF -DENABLE_PACKAGING=ON ..
make && make package
ls
