name: Linux Builds

on:
  workflow_call:
    inputs:
      build-type:
        required: true
        type: string

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: tfcollins/libiio_ubuntu_20_04-ci:latest
            artifact-name: Linux-Ubuntu-20.04
          - image: tfcollins/libiio_ubuntu_22_04-ci:latest
            artifact-name: Linux-Ubuntu-22.04
          - image: tfcollins/libiio_ubuntu_24_04-ci:latest
            artifact-name: Linux-Ubuntu-24.04
          - image: tfcollins/libiio_fedora_28-ci:latest
            artifact-name: Linux-Fedora-28
          - image: tfcollins/libiio_fedora_34-ci:latest
            artifact-name: Linux-Fedora-34
          - image: tfcollins/libiio_debian_bullseye-ci:latest
            artifact-name: Linux-Debian-11
          - image: tfcollins/libiio_debian_bookworm-ci:latest
            artifact-name: Linux-Debian-12
          - image: tfcollins/libiio_opensuse_15_4-ci:latest
            artifact-name: Linux-openSUSE-15.4
    container:
      image: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build
        run: |
          set -e
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} -Werror=dev -DCOMPILE_WARNING_AS_ERROR=ON -DENABLE_PACKAGING=ON -DCPP_BINDINGS=ON -DWITH_SERIAL_BACKEND=ON -DWITH_EMU_BACKEND=ON -DWITH_MAN=ON -DCPACK_SYSTEM_NAME=${{ matrix.artifact-name }}
          make VERBOSE=1
          cmake .. -DLICENSE_CHECK=ON
          make package
          make required2tar

      - name: Build with Examples
        if: matrix.artifact-name == 'Linux-Ubuntu-24.04'
        run: |
          set -e
          mkdir build-examples && cd build-examples
          cmake .. -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} -Werror=dev -DCOMPILE_WARNING_AS_ERROR=ON -DCPP_BINDINGS=ON -DWITH_SERIAL_BACKEND=ON -DWITH_EMU_BACKEND=ON -DWITH_EXAMPLES=ON -DCPP_EXAMPLES=ON
          make

      - name: Kernel check
        if: matrix.artifact-name == 'Linux-Ubuntu-22.04' && github.event_name == 'pull_request'
        run: ./CI/scripts/check_kernel.sh

      - name: README_BUILD check
        if: matrix.artifact-name == 'Linux-Ubuntu-22.04' && github.event_name == 'pull_request'
        run: ./CI/scripts/check_README_BUILD.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: |
            build/*.deb
            build/*.rpm
            build/*.tar.gz
